<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Micky" failures="3" tests="6" name="Test" time="5.247" errors="0" timestamp="2025-08-28T22:14:56 IST">
  <testcase classname="Scripts.AuthTesting" name="authtest" time="2.116">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;404&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at Scripts.AuthTesting.authtest(AuthTesting.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- authtest -->
  <testcase classname="Scripts.AuthTesting" name="getUsers_headerAndBodyChecks" time="0.618"/>
  <testcase classname="Scripts.NegativeTesting" name="createUser_emptyBody_shouldBeClientError" time="0.564">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected 4xx for empty body, but got 201 expected [true] but found [false],
	Error message should be there expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected 4xx for empty body, but got 201 expected [true] but found [false],
Error message should be there expected [true] but found [false]
at Scripts.NegativeTesting.createUser_emptyBody_shouldBeClientError(NegativeTesting.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- createUser_emptyBody_shouldBeClientError -->
  <testcase classname="Scripts.EndToEndTesting" name="createUser_extractId" time="0.801"/>
  <testcase classname="Scripts.EndToEndTesting" name="updateUser_put" time="1.105">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	PUT /users/{id} should return 200 expected [200] but found [503],
	PUT response missing &amp;apos;name&amp;apos;">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
PUT /users/{id} should return 200 expected [200] but found [503],
PUT response missing 'name'
at Scripts.EndToEndTesting.updateUser_put(EndToEndTesting.java:92)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- updateUser_put -->
  <testcase classname="Scripts.EndToEndTesting" name="deleteUser" time="0.0">
    <skipped/>
  </testcase> <!-- deleteUser -->
</testsuite> <!-- Test -->
